site_name: TYMaterials
theme:
  name: material
  font: 
    text: Roboto 500
  logo: assets/logo.svg
  favicon: favicon.ico
  features:
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:  

  - ST: 
    - ST/index.md
    - Unit1: ST/Unit1.md
    - Unit2: ST/Unit2.md
    - Unit3: ST/Unit3.md
    - Unit4: ST/Unit4.md
    - Unit5: ST/Unit5.md
    - ST-CAE-1-Question-Bank: ST/ST-CAE-1-Question-Bank.md
    - ST-CAE-2-Question-Bank: ST/ST-CAE-2-Question-Bank.md
    - ST-CAE-3-Question-Bank: ST/ST-CAE-3-Question-Bank.md

  - UDBMS: 
    - UDBMS/index.md
    - Unit1: UDBMS/Unit1.md
    - Unit2: UDBMS/Unit2.md
    - Unit3: UDBMS/Unit3.md
    - Unit4: UDBMS/Unit4.md
    - Unit5: UDBMS/Unit5.md
    - UDB-CAE-1-Question-Bank: UDBMS/UDBMS-CAE-1-Question-Bank.md
    - UDB-CAE-2-Question-Bank: UDBMS/UDBMS-CAE-2-Question-Bank.md
    - UDB-CAE-3-Question-Bank: UDBMS/UDBMS-CAE-3-Question-Bank.md

  - NLP: 
    - NLP/index.md
    - Unit1: NLP/Unit1.md
    - Unit2: NLP/Unit2.md
    - Unit3: NLP/Unit3.md
    - Unit4: NLP/Unit4.md
    - Unit5: NLP/Unit5.md
    - NLP-CAE-1-Question-Bank: NLP/NLP-CAE-1-Question-Bank.md
    - NLP-CAE-2-Question-Bank: NLP/NLP-CAE-2-Question-Bank.md
    - NLP-CAE-3-Question-Bank: NLP/NLP-CAE-3-Question-Bank.md

  - SAMD: 
    - SAMD/index.md
    - Unit1: SAMD/Unit1.md
    - Unit2: SAMD/Unit2.md
    - Unit3: SAMD/Unit3.md
    - Unit4: SAMD/Unit4.md
    - Unit5: SAMD/Unit5.md
    - SAMD-CAE-1-Question-Bank: SAMD/SAMD-CAE-1-Question-Bank.md
    - SAMD-CAE-2-Question-Bank: SAMD/SAMD-CAE-2-Question-Bank.md
    - SAMD-CAE-3-Question-Bank: SAMD/SAMD-CAE-3-Question-Bank.md

  - UHV: 
    - UHV/index.md
    - Unit1: UHV/Unit1.md
    - Unit2: UHV/Unit2.md
    - Unit3: UHV/Unit3.md
    - Unit4: UHV/Unit4.md
    - Unit5: UHV/Unit5.md
    - SAMD-CAE-1-Question-Bank: UHV/UHV-CAE-1-Question-Bank.md
    - SAMD-CAE-2-Question-Bank: UHV/UHV-CAE-2-Question-Bank.md
    - SAMD-CAE-3-Question-Bank: UHV/UHV-CAE-3-Question-Bank.md

  - ML: 
    - ML/index.md
    - Unit1: ML/Unit1.md
    - Unit2: ML/Unit2.md
    - Unit3: ML/Unit3.md
    - Unit4: ML/Unit4.md
    - Unit5: ML/Unit5.md
    - Unit6: ML/Unit6.md
    - ML-CAE-1-Question-Bank: ML/ML-CAE-1-Question-Bank.md
    - ML-CAE-2-Question-Bank: ML/ML-CAE-2-Question-Bank.md
    - ML-CAE-3-Question-Bank: ML/ML-CAE-3-Question-Bank.md

  - SEPM: 
    - sepm/index.md
    - Unit1: sepm/Unit1.md
    - Unit2: sepm/Unit2.md
    - Unit3: sepm/Unit3.md
    - Unit4: sepm/Unit4.md
    - Unit5: sepm/Unit5.md
    - SEPM-CAE-1-Question-Bank: sepm/SEPM-CAE-1-Question-Bank.md
    - SEPM-CAE-2-Question-Bank: sepm/SEPM-CAE-2-Question-Bank.md
    - SEPM-CAE-3-Question-Bank: sepm/SEPM-CAE-3-Question-Bank.md
 
  - WD:
    - WD/index.md
    - Unit1: WD/Unit1.md
    - Unit2: WD/Unit2.md
    - Unit3: WD/Unit3.md
    - Unit4: WD/Unit4.md
    - Unit5: WD/Unit5.md
    - WD-CAE-1-Question-Bank: WD/WD-CAE-1-Question-Bank.md
    - WD-CAE-2-Question-Bank: WD/WD-CAE-2-Question-Bank.md
    - WD-CAE-3-Question-Bank: WD/WD-CAE-3-Question-Bank.md
  
  - DBMS:
    - dbms/index.md
    - Unit1: dbms/Unit1.md
    - Unit2: dbms/Unit2.md
    - Unit3: dbms/Unit3.md
    - Unit4: dbms/Unit4.md
    - Unit5: dbms/Unit5.md
    - SQL-Cheat-Sheet: dbms/SQL-Cheat-Sheet.md
    - DBMS-CAE-1-Question-Bank: dbms/DBMS-CAE-1-Question-Bank.md
    - DBMS-CAE-2-Question-Bank: dbms/DBMS-CAE-2-Question-Bank.md
    - DBMS-CAE-3-Question-Bank: dbms/DBMS-CAE-3-Question-Bank.md

  - CD:
    - cd/index.md
    - Unit1: cd/Unit1.md
    - Unit2: cd/Unit2.md
    - Unit3: cd/Unit3.md
    - Unit4: cd/Unit4.md
    - Unit5: cd/Unit5.md
    - CD-CAE-1-Question-Bank: cd/CD-CAE-1-Question-Bank.md
    - CD-CAE-2-Question-Bank: cd/CD-CAE-2-Question-Bank.md
    - CD-CAE-3-Question-Bank: cd/CD-CAE-3-Question-Bank.md
  
  - EEIM:
    - eeim/index.md
    - Unit1: eeim/Unit1.md
    - Unit2: eeim/Unit2.md
    - Unit3: eeim/Unit3.md
    - Unit4: eeim/Unit4.md
    - Unit5: eeim/Unit5.md
    - EEIM-CAE-1-Question-Bank: eeim/EEIM-CAE-1-Question-Bank.md
    - EEIM-CAE-2-Question-Bank: eeim/EEIM-CAE-2-Question-Bank.md

  - BIA:
    - BIA/index.md
    - Unit1: BIA/Unit1.md
    - Unit2: BIA/Unit2.md
    - Unit3: BIA/Unit3.md
    - Unit4: BIA/Unit4.md
    - Unit5: BIA/Unit5.md
    - BIA-CAE-2-Question-Bank: BIA/BIA-CAE-2-Question-Bank.md
    - BIA-CAE-3-Question-Bank: BIA/BIA-CAE-3-Question-Bank.md

  - DM:
    - DM/index.md
    - Unit1: DM/Unit1.md
    - Unit2: DM/Unit2.md
    - Unit3: DM/Unit3.md
    - Unit4: DM/Unit4.md
    - Unit5: DM/Unit5.md
    - DM-CAE-2-Question-Bank: DM/DM-CAE-2-Question-Bank.md
  
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gautampatil1
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/gautampatil1
    - icon: fontawesome/brands/discord
      link: upi://pay?pa=8625057783@airtel&pn=GAUTAM SURESH PATIL&tn=Pay money to GAUTAM SURESH PATIL
  generator: false
  analytics:
    provider: google 
    property: G-B5944EDZSE

extra_javascript:
  - lol.js

copyright: Copyright &copy; 2023 Gautam Patil
