site_name: TYMaterials
theme:
  name: material
  font: 
    text: Roboto 500
  logo: assets/logo.svg
  favicon: favicon.ico
  features:
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


nav:
  - SEPM: 
    - sepm/index.md
    - Unit1: sepm/Unit1.md
    - Unit2: sepm/Unit2.md
    - Unit3: sepm/Unit3.md
    - Unit4: sepm/Unit4.md
    - Unit5: sepm/Unit5.md
    - SEPM-CAE-1-Question-Bank: sepm/SEPM-CAE-1-Question-Bank.md
    - SEPM-CAE-2-Question-Bank: sepm/SEPM-CAE-2-Question-Bank.md
  
  - WD:
    - WD/index.md
    - Unit1: WD/Unit1.md
    - Unit2: WD/Unit2.md
    - Unit3: WD/Unit3.md
    - Unit4: WD/Unit4.md
    - Unit5: WD/Unit5.md
    - WD-CAE-1-Question-Bank: WD/WD-CAE-1-Question-Bank.md
    - WD-CAE-2-Question-Bank: WD/WD-CAE-2-Question-Bank.md
  
  - DBMS:
    - dbms/index.md
    - Unit1: dbms/Unit1.md
    - Unit2: dbms/Unit2.md
    - Unit3: dbms/Unit3.md
    - Unit4: dbms/Unit4.md
    - Unit5: dbms/Unit5.md
    - DBMS-CAE-1-Question-Bank: dbms/DBMS-CAE-1-Question-Bank.md
    - DBMS-CAE-2-Question-Bank: dbms/DBMS-CAE-2-Question-Bank.md

  - CD:
    - cd/index.md
    - Unit1: cd/Unit1.md
    - Unit2: cd/Unit2.md
    - Unit3: cd/Unit3.md
    - Unit4: cd/Unit4.md
    - Unit5: cd/Unit5.md
    - CD-CAE-1-Question-Bank: cd/CD-CAE-1-Question-Bank.md
    - CD-CAE-2-Question-Bank: cd/CD-CAE-2-Question-Bank.md
  
  - EEIM:
    - eeim/index.md
    - Unit1: eeim/Unit1.md
    - Unit2: eeim/Unit2.md
    - Unit3: eeim/Unit3.md
    - Unit4: eeim/Unit4.md
    - Unit5: eeim/Unit5.md
    - EEIM-CAE-1-Question-Bank: eeim/EEIM-CAE-1-Question-Bank.md
    - EEIM-CAE-2-Question-Bank: eeim/EEIM-CAE-2-Question-Bank.md

  - BIA:
    - BIA-CAE-2-Question-Bank: BIA/BIA-CAE-2-Question-Bank.md

  - DM:
    - DM-CAE-2-Question-Bank: DM/DM-CAE-2-Question-Bank.md
  
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gautampatil1
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/gautampatil1
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mQPNB5hT
  generator: false
  analytics:
    provider: google 
    property: G-B5944EDZSE

extra_javascript:
  - lol.js

copyright: Copyright &copy; 2023 Gautam Patil
